[package]
name = "kilo-ed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.1"
crossterm = "0.23.2"
errno = "0.2.8"
xdg = "2.4.1"

[features]
keystroke_log = []
